networks:
  earth_orbit_network:
    ipam:
      config:
      - subnet: 172.21.0.0/16
  earth_surface_network:
    ipam:
      config:
      - subnet: 172.20.0.0/16
  moon_orbit_network:
    ipam:
      config:
      - subnet: 172.23.0.0/16
  moon_surface_network:
    ipam:
      config:
      - subnet: 172.22.0.0/16
services:
  earth_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_orbit_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.2
    ports:
    - 50002:5001
    privileged: true
    tty: true
  earth_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_surface_1
    networks:
      earth_surface_network:
        ipv4_address: 172.20.1.2
    ports:
    - 50000:5001
    privileged: true
    tty: true
  earth_surface_2:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_surface_2
    networks:
      earth_surface_network:
        ipv4_address: 172.20.2.2
    ports:
    - 50001:5001
    privileged: true
    tty: true
  moon_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_orbit_1
    networks:
      moon_orbit_network:
        ipv4_address: 172.23.1.2
    ports:
    - 50003:5001
    privileged: true
    tty: true
  moon_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_1
    networks:
      moon_surface_network:
        ipv4_address: 172.22.1.2
    ports:
    - 50004:5001
    privileged: true
    tty: true
  moon_surface_2:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_2
    networks:
      moon_surface_network:
        ipv4_address: 172.22.2.2
    ports:
    - 50005:5001
    privileged: true
    tty: true
  moon_surface_3:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_3
    networks:
      moon_surface_network:
        ipv4_address: 172.22.3.2
    ports:
    - 50006:5001
    privileged: true
    tty: true
  relay_earth_orbit_moon_orbit:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_orbit_moon_orbit
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.0.3
      moon_orbit_network:
        ipv4_address: 172.23.0.3
    ports:
    - 50010:5001
    privileged: true
    tty: true
  relay_earth_orbit_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_orbit_moon_surface
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.0.4
      moon_surface_network:
        ipv4_address: 172.22.0.3
    ports:
    - 50011:5001
    privileged: true
    tty: true
  relay_earth_surface_earth_orbit:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_surface_earth_orbit
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.0.2
      earth_surface_network:
        ipv4_address: 172.20.0.2
    ports:
    - 50007:5001
    privileged: true
    tty: true
  relay_earth_surface_moon_orbit:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_surface_moon_orbit
    networks:
      earth_surface_network:
        ipv4_address: 172.20.0.3
      moon_orbit_network:
        ipv4_address: 172.23.0.2
    ports:
    - 50008:5001
    privileged: true
    tty: true
  relay_earth_surface_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_earth_surface_moon_surface
    networks:
      earth_surface_network:
        ipv4_address: 172.20.0.4
      moon_surface_network:
        ipv4_address: 172.22.0.2
    ports:
    - 50009:5001
    privileged: true
    tty: true
  relay_moon_orbit_moon_surface:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: relay_moon_orbit_moon_surface
    networks:
      moon_orbit_network:
        ipv4_address: 172.23.0.4
      moon_surface_network:
        ipv4_address: 172.22.0.4
    ports:
    - 50012:5001
    privileged: true
    tty: true
version: '3'
